// Splits SEMANTICS.md into docs/contract/NN-slug.md — one page per
// `## ` section, each stamped as generated. CI regenerates and fails on
// any diff, so "the docs are generated from the contract" is a machine
// invariant, not a promise. Dependency-free on purpose.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'docs', 'contract');
const source = readFileSync(join(root, 'SEMANTICS.md'), 'utf8');

const BANNER = (title) =>
  `<!-- GENERATED from SEMANTICS.md ("${title}") by scripts/build-docs.mjs — do not edit here; edit SEMANTICS.md and run \`npm run docs\`. -->\n\n`;

function slugify(heading) {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
}

// Preamble = everything before the first `## `; then one chunk per section.
const lines = source.split('\n');
const sections = [];
let current = { title: 'Harkara — Delivery Semantics (preamble)', slug: 'preamble', body: [] };
for (const line of lines) {
  if (line.startsWith('## ')) {
    sections.push(current);
    const title = line.slice(3).trim();
    current = { title, slug: slugify(title), body: [line] };
  } else {
    current.body.push(line);
  }
}
sections.push(current);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const index = [
  '<!-- GENERATED by scripts/build-docs.mjs — do not edit. -->',
  '',
  '# The contract, one page per section',
  '',
  'Source of truth: [SEMANTICS.md](../../SEMANTICS.md). If a page here and',
  'the source disagree, run `npm run docs` — the source wins.',
  '',
];
sections.forEach((section, i) => {
  const number = String(i).padStart(2, '0');
  const file = `${number}-${section.slug}.md`;
  const body = section.body.join('\n').replace(/\n+$/, '\n');
  writeFileSync(join(outDir, file), BANNER(section.title) + body);
  index.push(`- [${section.title}](${file})`);
});
writeFileSync(join(outDir, 'README.md'), index.join('\n') + '\n');

console.log(
  `docs/contract: ${String(readdirSync(outDir).length)} files from ${String(sections.length)} sections`,
);
